### ISSUE TITLE
Unable to upload .bin file

### ISSUE THREAD

**Issue by sithsah** [SolarCarChallenge/pi-top#4]
I have tried to upload a program for about a day now and I keep running into the same error. The output is available [here](https://pastebin.com/YixHK5vC). The Arduino IDE detects the board as `Arduino/Genuino Zero (Native USB Port)` and I have tried selecting both native and programming port options. How do I flash the .bin file onto the chip?

**Comment by gte718p** [comment]
I have not tried flashing a .bin file directly.  I have opened the ino file, and let Arduino compile it and load it.  I'll go back and look at my settings this evening and see if there is anything else special that needs to happen.

**Comment by sithsah** [comment]
I tried going through the Arduino IDE, but it gave me the same error message. I found a way to compile the code into a .bin file, so all I need to do now is flash it. I can give you a list of my settings if you want to debug that way.

**Comment by gte718p** [comment]
So the JTAG error is because you are using the wrong programmer.  You should be using Atmel-ICE (AVR).  The JTAG programmer requires additional hardware.

I'm not seeing any issues compiling in the .ino Arduino IDE.  It is important to enter there Pairing ID in line 17.  Otherwise it will not compile.  I am having problems getting the installed IDE to upload.  I'm getting COM port busy error.  I'm working on figuring that out.  However, the web IDE is having no issues uploading.

If that doesn't work, we will dig a little deeper.

**Comment by sithsah** [comment]
Here is a [screenshot](https://snag.gy/Bu71qy.jpg) of my attempted upload. To make sure it has nothing to do with the code, I used an empty sketch for testing. I switched to `Atmel-ICE (AVR)` and the same error appears.

**Comment by gte718p** [comment]
I have asked Rez and Wil who designed the board to chime in.  It is sounding like a driver issue to me.

I'm assuming you found the walk through.
https://github.com/SolarCarChallenge/pi-top/blob/master/Helios%20Board/Getting%20on%20the%20road%20with%20pi-topHELIOS.pdf

I set up a new machine from scratch yesterday as I knew mine was working, but I didn't remember all the thing I have done to make it work over the last year.  I fought with it for three hours because I kept getting a COM busy error.  I switched to a different USB port and it worked.

Not the greatest and most profound suggestion ever, but maybe try another machine?  

Jarrett

**Comment by sithsah** [comment]
I seem to have missed the walkthrough when I first cloned the repo. I tried uploading on my laptop and it worked after a few changes. I was on the programming port instead of the native one and I didn't know that there was a bootloader mode for the board.

The only inconvenience I have now is that it usually takes multiple tries for the upload to go through, but it works, so that's what matters. Thanks.
